CREATE SEQUENCE SEQ_CATEGORY_CODE;
DROP TABLE TB_INFO CASCADE CONSTRAINTS;

CREATE TABLE TB_INFO
(
  CATEGORY_CODE NUMBER NOT NULL CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY
, CATEGORY_NAME VARCHAR2(20) NOT NULL
, REF_CATEGORY_CODE NUMBER 
, FIXED_Y_N VARCHAR2(10)
);

ALTER TABLE TB_INFO
ADD CONSTRAINT FK_REF_CATEGORY_CODE FOREIGN KEY ( REF_CATEGORY_CODE )
REFERENCES TB_INFO ( CATEGORY_CODE );


COMMENT ON COLUMN TB_INFO.CATEGORY_CODE IS '유형 코드';
COMMENT ON COLUMN TB_INFO.CATEGORY_NAME IS '이름';
COMMENT ON COLUMN TB_INFO.REF_CATEGORY_CODE IS '상위 유형 코드';
COMMENT ON COLUMN TB_INFO.FIXED_Y_N IS '고정 여부';
-- 새로 만들때는 1번 2번임
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '연주' , 'Y');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '연주' , 'N');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '레슨' , 'Y');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '레슨' , 'N');

INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, REF_CATEGORY_CODE, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '오브리' , 1 , 'Y');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, REF_CATEGORY_CODE, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '오브리' , 2 , 'N');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, REF_CATEGORY_CODE, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '방과후' , 3 , 'Y');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, REF_CATEGORY_CODE, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '새끼레슨' , 4 , 'N');
INSERT INTO TB_INFO (CATEGORY_CODE, CATEGORY_NAME, REF_CATEGORY_CODE, FIXED_Y_N) VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '취미생 레슨' , 3 , 'Y');
-- 여기까지

CREATE SEQUENCE SEQ_SCHEDULE_CODE;
DROP TABLE TB_SCHEDULE CASCADE CONSTRAINTS;
CREATE TABLE TB_SCHEDULE
(
  SCHEDULE_CODE NUMBER CONSTRAINT PK_SCHEDULE_CODE PRIMARY KEY
, SCHEDULE_NAME VARCHAR2(100) NOT NULL 
, SCHEDULE_DATE VARCHAR2(50) 
, SCHEDULE_TIME VARCHAR2(30) 
, SCHEDULE_PAY NUMBER NOT NULL
, CATEGORY_CODE NUMBER CONSTRAINT FK_CATEGORY_CODE REFERENCES TB_INFO(CATEGORY_CODE)
, SCHEDULE_NOTE VARCHAR2(50) NOT NULL
);
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_CODE IS '스케줄 코드';
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_NAME IS '행사 이름';
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_DATE IS '행사 날짜';
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_TIME IS '행사 시간';
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_PAY IS '보수(만원)';
COMMENT ON COLUMN TB_SCHEDULE.CATEGORY_CODE IS '유형 코드';
COMMENT ON COLUMN TB_SCHEDULE.SCHEDULE_NOTE IS '특이사항';

-- 카테고리 코드 하위카테고리코드로 지정해주어야함

INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '화성 서신중학교' , '매주 월요일' , '14:20 ~ 16:00' , 8 , 7,'2층 기술가정실 2~3학년 수업');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '화성 서신중학교' , '매주 목요일' , '14:20 ~ 16:00' , 8 , 7,'2층 기술가정실 1학년 수업');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '화성 장안초등학교' , '매주 화요일' , '14:50 ~ 160:00' , 10 , 7,'3층 주산암산교실');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '용인 새에덴교회' , '매주 일요일' , '09:00 ~ 13:30' , 10 , 5,'3층 합창실');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '서초동 연습실' , 4 , 8,'레슨 끝나고 날짜맞춰서');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '전광우색소폰스튜디오' , '매주 금요일' , '19:00 ~ 20:00' , 4 , 9,'열심히하심');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '전광우색소폰스튜디오' , '매주 금요일' , '20:00 ~ 21:00' , 4 , 9,'2월 향상 예정');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '전광우색소폰스튜디오' , '매주 토요일' , '20:00 ~ 21:00' , 4 , 9,'제주도의 푸른 밤');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '목동 필하모닉 오케스트라 창단연주회' , '11.29 화' , '19:00 ~ 22:00' , 17 , 6,'네이버 필하모닉 오케스트라 지하 1층');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '계성초등학교 정기연주회' , '11.30 수' , '13:30 ~ 16:00' , 5 , 6,'연습');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '계성초등학교 정기연주회' , '12.2 금' , '15:00 ~ 16:00' , 5 , 6,'연습');
INSERT INTO TB_SCHEDULE (SCHEDULE_CODE,SCHEDULE_NAME,SCHEDULE_DATE,SCHEDULE_TIME,SCHEDULE_PAY,CATEGORY_CODE,SCHEDULE_NOTE)  
VALUES (SEQ_SCHEDULE_CODE.NEXTVAL , '계성초등학교 정기연주회' , '12.3 토' , '10:00 , 14:30' , 20 , 6,'연주 2회');

commit;
